DScurso = [
    {"CODIGO": "123456", "NOME": "SISTEMAS DE INFORMACAO", "DURACAO": 4},
    {"CODIGO": "456789", "NOME": "ENGENHARIA DE SOFTWARE", "DURACAO": 5},
    {"CODIGO": "987123", "NOME": "CIENCIA DE DADOS", "DURACAO": 4},
    {"CODIGO": "567123", "NOME": "NEGOCIOS DIGITAIS", "DURACAO": 4},
    {"CODIGO": "789432", "NOME": "CIENCIA DA COMPUTACAO", "DURACAO": 5},
]
DSdisciplinas = [
    {"CODIGOCURSO": "789432", "CODIGODISCIPLINA": "9031", "DISCIPLINA": "ALGORITMOS E LÓGICA DE PROGRAMACAO I", "HORASAULAS": 120},
    {"CODIGOCURSO": "987123", "CODIGODISCIPLINA": "3317", "DISCIPLINA": "MINERACAOD E DADOS I", "HORASAULAS": 80},
    {"CODIGOCURSO": "987123", "CODIGODISCIPLINA": "1418", "DISCIPLINA": "MINERACAOD E DADOS II", "HORASAULAS": 80},
    {"CODIGOCURSO": "789432", "CODIGODISCIPLINA": "9032", "DISCIPLINA": "ALGORITMOS E LÓGICA DE PROGRAMACAO II", "HORASAULAS": 80},
    {"CODIGOCURSO": "789432", "CODIGODISCIPLINA": "9033", "DISCIPLINA": "ALGORITMOS E LÓGICA DE PROGRAMACAO III", "HORASAULAS": 120},
    {"CODIGOCURSO": "456789", "CODIGODISCIPLINA": "4219", "DISCIPLINA": "MINERACAO DE DADOS II", "HORASAULAS": 80},
    {"CODIGOCURSO": "456789", "CODIGODISCIPLINA": "1034", "DISCIPLINA": "PROJETO INTEGRADOR I", "HORASAULAS": 40},
    {"CODIGOCURSO": "567123", "CODIGODISCIPLINA": "6518", "DISCIPLINA": "MODELAGEM DE NEGOCIOS DIGITAIS I", "HORASAULAS": 80},
    {"CODIGOCURSO": "567123", "CODIGODISCIPLINA": "6618", "DISCIPLINA": "MODELAGEM DE NEGOCIOS DIGITAIS II", "HORASAULAS": 120},
    {"CODIGOCURSO": "789432", "CODIGODISCIPLINA": "9047", "DISCIPLINA": "BANCO DE DADOS: APLICACAO", "HORASAULAS": 80},
    {"CODIGOCURSO": "567123", "CODIGODISCIPLINA": "6303", "DISCIPLINA": "PROGRAMACAO WEB", "HORASAULAS": 80},
    {"CODIGOCURSO": "567123", "CODIGODISCIPLINA": "6342", "DISCIPLINA": "BANCO DE DADOS I", "HORASAULAS": 80},
    {"CODIGOCURSO": "789432", "CODIGODISCIPLINA": "9059", "DISCIPLINA": "BANCO DE DADOS: SEGURANCA", "HORASAULAS": 80},
    {"CODIGOCURSO": "789432", "CODIGODISCIPLINA": "9058", "DISCIPLINA": "BANCO DE DADOS: CRIPTOGRAFICA", "HORASAULAS": 80},
    {"CODIGOCURSO": "789432", "CODIGODISCIPLINA": "9162", "DISCIPLINA": "PROJETO INTEGRADOR I", "HORASAULAS": 120},
    {"CODIGOCURSO": "789432", "CODIGODISCIPLINA": "9264", "DISCIPLINA": "PROJETO INTEGRADOR II", "HORASAULAS": 120},
    {"CODIGOCURSO": "789432", "CODIGODISCIPLINA": "9071", "DISCIPLINA": "MINERACAO DE DADOS I", "HORASAULAS": 80},
    {"CODIGOCURSO": "456789", "CODIGODISCIPLINA": "2923", "DISCIPLINA": "PROJETO INTEGRADOR II", "HORASAULAS": 40},
    {"CODIGOCURSO": "987123", "CODIGODISCIPLINA": "0301", "DISCIPLINA": "ALGORITMOS COM PYTHON I", "HORASAULAS": 80},
    {"CODIGOCURSO": "789432", "CODIGODISCIPLINA": "9279", "DISCIPLINA": "MINERACAO DE DADOS II", "HORASAULAS": 80},
    {"CODIGOCURSO": "567123", "CODIGODISCIPLINA": "6437", "DISCIPLINA": "BANCO DE DADOS II", "HORASAULAS": 80},
    {"CODIGOCURSO": "567123", "CODIGODISCIPLINA": "6419", "DISCIPLINA": "METODOLOGIAS ÁGEIS", "HORASAULAS": 80},
    {"CODIGOCURSO": "789432", "CODIGODISCIPLINA": "9372", "DISCIPLINA": "ESTATISTICA I", "HORASAULAS": 80},
    {"CODIGOCURSO": "789432", "CODIGODISCIPLINA": "9384", "DISCIPLINA": "ESTATISTICA II", "HORASAULAS": 40},
    {"CODIGOCURSO": "789432", "CODIGODISCIPLINA": "9392", "DISCIPLINA": "INTELIGENCIA ARTIFICIAL I", "HORASAULAS": 160},
    {"CODIGOCURSO": "987123", "CODIGODISCIPLINA": "1302", "DISCIPLINA": "ALGORITMOS COM PYTHON II", "HORASAULAS": 80},
    {"CODIGOCURSO": "987123", "CODIGODISCIPLINA": "2303", "DISCIPLINA": "ALGORITMOS COM PYTHON III", "HORASAULAS": 80},
    {"CODIGOCURSO": "789432", "CODIGODISCIPLINA": "9032", "DISCIPLINA": "BANCO DE DADOS: CONCEITOS", "HORASAULAS": 80},
    {"CODIGOCURSO": "987123", "CODIGODISCIPLINA": "8302", "DISCIPLINA": "ESTATISTICA I", "HORASAULAS": 40},
    {"CODIGOCURSO": "987123", "CODIGODISCIPLINA": "3304", "DISCIPLINA": "ESTATISTICA II", "HORASAULAS": 40},
    {"CODIGOCURSO": "789432", "CODIGODISCIPLINA": "9384", "DISCIPLINA": "INTELIGENCIA ARTIFICIAL II", "HORASAULAS": 160},
    {"CODIGOCURSO": "123456", "CODIGODISCIPLINA": "0001", "DISCIPLINA": "ALGORITMOS I", "HORASAULAS": 80},
    {"CODIGOCURSO": "123456", "CODIGODISCIPLINA": "1002", "DISCIPLINA": "ALGORITMOS II", "HORASAULAS": 80},
    {"CODIGOCURSO": "123456", "CODIGODISCIPLINA": "2003", "DISCIPLINA": "ALGORITMOS III", "HORASAULAS": 80},
    {"CODIGOCURSO": "123456", "CODIGODISCIPLINA": "1042", "DISCIPLINA": "BANCO DE DADOS I", "HORASAULAS": 80},
    {"CODIGOCURSO": "567123", "CODIGODISCIPLINA": "6177", "DISCIPLINA": "PROJETO INTEGRADOR I", "HORASAULAS": 60},
    {"CODIGOCURSO": "987123", "CODIGODISCIPLINA": "1302", "DISCIPLINA": "PROJETO INTEGRADOR I", "HORASAULAS": 40},
    {"CODIGOCURSO": "987123", "CODIGODISCIPLINA": "2304", "DISCIPLINA": "PROJETO INTEGRADOR II", "HORASAULAS": 40},
    {"CODIGOCURSO": "567123", "CODIGODISCIPLINA": "6287", "DISCIPLINA": "PROJETO INTEGRADOR II", "HORASAULAS": 120},
    {"CODIGOCURSO": "123456", "CODIGODISCIPLINA": "2037", "DISCIPLINA": "BANCO DE DADOS II", "HORASAULAS": 80},
    {"CODIGOCURSO": "123456", "CODIGODISCIPLINA": "3019", "DISCIPLINA": "BANCO DE DADOS III", "HORASAULAS": 80},
    {"CODIGOCURSO": "123456", "CODIGODISCIPLINA": "4018", "DISCIPLINA": "BANCO DE DADOS IV", "HORASAULAS": 80},
    {"CODIGOCURSO": "987123", "CODIGODISCIPLINA": "1342", "DISCIPLINA": "BANCO DE DADOS I", "HORASAULAS": 80},
    {"CODIGOCURSO": "987123", "CODIGODISCIPLINA": "2338", "DISCIPLINA": "BANCO DE DADOS II", "HORASAULAS": 80},
    {"CODIGOCURSO": "123456", "CODIGODISCIPLINA": "1102", "DISCIPLINA": "PROJETO INTEGRADOR I", "HORASAULAS": 40},
    {"CODIGOCURSO": "123456", "CODIGODISCIPLINA": "2204", "DISCIPLINA": "PROJETO INTEGRADOR II", "HORASAULAS": 40},
    {"CODIGOCURSO": "456789", "CODIGODISCIPLINA": "0007", "DISCIPLINA": "ALGORITMOS E LÓGICA I", "HORASAULAS": 80},
    {"CODIGOCURSO": "456789", "CODIGODISCIPLINA": "1008", "DISCIPLINA": "ALGORITMOS E LÓGICA II", "HORASAULAS": 80},
    {"CODIGOCURSO": "567123", "CODIGODISCIPLINA": "6201", "DISCIPLINA": "ALGORITMOS COM JAVA I", "HORASAULAS": 80},
    {"CODIGOCURSO": "567123", "CODIGODISCIPLINA": "6202", "DISCIPLINA": "ALGORITMOS COM JAVA II", "HORASAULAS": 80},
    {"CODIGOCURSO": "456789", "CODIGODISCIPLINA": "2009", "DISCIPLINA": "ALGORITMOS E LÓGICA III", "HORASAULAS": 80},
    {"CODIGOCURSO": "456789", "CODIGODISCIPLINA": "1020", "DISCIPLINA": "BANCO DE DADOS: CONCEITOS", "HORASAULAS": 80},
    {"CODIGOCURSO": "456789", "CODIGODISCIPLINA": "2015", "DISCIPLINA": "BANCO DE DADOS: APLICACAO", "HORASAULAS": 80},
    {"CODIGOCURSO": "987123", "CODIGODISCIPLINA": "6302", "DISCIPLINA": "INTELIGENCIA ARTIFICIAL I", "HORASAULAS": 120},
    {"CODIGOCURSO": "987123", "CODIGODISCIPLINA": "7304", "DISCIPLINA": "INTELIGENCIA ARTIFICIAL II", "HORASAULAS": 120},
    {"CODIGOCURSO": "456789", "CODIGODISCIPLINA": "3011", "DISCIPLINA": "MINERACAO DE DADOS I", "HORASAULAS": 80},
]


def list_cursos(cursos):
    resp = ['Os cursos são:']
    for curso in cursos:
        resp.append(curso['NOME'] + ',')
    resp.append(f'totalizando: {len(cursos)} cursos!')
    return ' '.join(resp)


def get_curso_name(cod_curso, cursos):
    for curso in cursos:
        if cod_curso == curso['CODIGO']:
            return curso["NOME"], curso["DURACAO"]


def get_curso_id(nome_curso, cursos):
    for curso in cursos:
        if nome_curso == curso['NOME']:
            return curso["CODIGO"], curso["DURACAO"]


def get_disciplinas_id(id_curso, disciplinas):
    resp = []
    for disc in disciplinas:
        if disc["CODIGOCURSO"] == id_curso:
            resp.append(disc["DISCIPLINA"])
    return resp


def get_disciplinas_name(nome_curso, cursos, disciplinas):
    id = get_curso_id(nome_curso, cursos)[0]
    return get_disciplinas_id(id, disciplinas)


def get_cargatotal_id(id_curso, disciplinas):
    soma = []
    for disc in disciplinas:
        if disc['CODIGOCURSO'] == id_curso:
            soma.append(int(disc["HORASAULAS"]))
    return f'A Soma das horas são: {sum(soma)}h'


def get_cargatotal_name(nome_curso, cursos, disciplinas):
    id = get_curso_id(nome_curso, cursos)[0]
    return get_cargatotal_id(id, disciplinas)


def get_curso_disc(nome_disc, disciplinas, cursos):
    crs_id = []
    crs_name = []
    for disc in disciplinas:
        if disc["DISCIPLINA"] == nome_disc:
            if disc['CODIGOCURSO'] not in crs_id:
                crs_id.append(disc['CODIGOCURSO'])

    for c_id in crs_id:
        nome = get_curso_name(c_id, cursos)[0]
        crs_name.append(nome)

    return crs_name


def get_all(id_curso, disciplinas):
    resp = ['break']
    for disc in disciplinas:
        if disc['CODIGOCURSO'] == id_curso:
            resp.append(f'Código: {disc["CODIGODISCIPLINA"]}')
            resp.append(f'Nome: {disc["DISCIPLINA"]}')
            resp.append(f'Carga Horária: {disc["HORASAULAS"]}')
            resp.append('break')
    return str(resp).replace('break', '\n')





