# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deletar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(798, 713)
        Form.setStyleSheet("\n"
"background-color: rgb(226, 226, 226);")
        self.Logo = QtWidgets.QLabel(Form)
        self.Logo.setGeometry(QtCore.QRect(210, -10, 371, 301))
        self.Logo.setStyleSheet("\n"
"background-color: rgb(226, 226, 226);")
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("Imagens/LOGO GERAL.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.deletarButton = QtWidgets.QPushButton(Form)
        self.deletarButton.setGeometry(QtCore.QRect(250, 520, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(17)
        self.deletarButton.setFont(font)
        self.deletarButton.setMouseTracking(False)
        self.deletarButton.setAutoFillBackground(False)
        self.deletarButton.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.deletarButton.setIconSize(QtCore.QSize(32, 32))
        self.deletarButton.setCheckable(False)
        self.deletarButton.setAutoDefault(False)
        self.deletarButton.setDefault(False)
        self.deletarButton.setFlat(False)
        self.deletarButton.setObjectName("deletarButton")
        self.amostraBox = QtWidgets.QComboBox(Form)
        self.amostraBox.setGeometry(QtCore.QRect(260, 350, 301, 22))
        self.amostraBox.setObjectName("amostraBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.deletarButton.setText(_translate("Form", "DELETAR AMOSTRA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
