# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inserir.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(798, 713)
        Form.setStyleSheet("\n"
"background-color: rgb(226, 226, 226);")
        self.Logo = QtWidgets.QLabel(Form)
        self.Logo.setGeometry(QtCore.QRect(220, -10, 351, 271))
        self.Logo.setStyleSheet("\n"
"background-color: rgb(226, 226, 226);")
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("Imagens/LOGO GERAL.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.inserirButton = QtWidgets.QPushButton(Form)
        self.inserirButton.setGeometry(QtCore.QRect(250, 620, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(17)
        self.inserirButton.setFont(font)
        self.inserirButton.setMouseTracking(False)
        self.inserirButton.setAutoFillBackground(False)
        self.inserirButton.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.inserirButton.setIconSize(QtCore.QSize(32, 32))
        self.inserirButton.setCheckable(False)
        self.inserirButton.setAutoDefault(False)
        self.inserirButton.setDefault(False)
        self.inserirButton.setFlat(False)
        self.inserirButton.setObjectName("inserirButton")
        self.lineMp25 = QtWidgets.QLineEdit(Form)
        self.lineMp25.setGeometry(QtCore.QRect(280, 390, 251, 20))
        self.lineMp25.setText("")
        self.lineMp25.setObjectName("lineMp25")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(280, 370, 251, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(280, 420, 251, 16))
        self.label_2.setObjectName("label_2")
        self.lineO3 = QtWidgets.QLineEdit(Form)
        self.lineO3.setGeometry(QtCore.QRect(280, 440, 251, 20))
        self.lineO3.setText("")
        self.lineO3.setObjectName("lineO3")
        self.lineCo = QtWidgets.QLineEdit(Form)
        self.lineCo.setGeometry(QtCore.QRect(280, 490, 251, 20))
        self.lineCo.setText("")
        self.lineCo.setObjectName("lineCo")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(280, 470, 251, 16))
        self.label_3.setObjectName("label_3")
        self.lineNo2 = QtWidgets.QLineEdit(Form)
        self.lineNo2.setGeometry(QtCore.QRect(280, 540, 251, 20))
        self.lineNo2.setText("")
        self.lineNo2.setObjectName("lineNo2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(280, 520, 251, 16))
        self.label_4.setObjectName("label_4")
        self.lineSo2 = QtWidgets.QLineEdit(Form)
        self.lineSo2.setGeometry(QtCore.QRect(280, 590, 251, 20))
        self.lineSo2.setText("")
        self.lineSo2.setObjectName("lineSo2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(280, 570, 251, 16))
        self.label_5.setObjectName("label_5")
        self.mp10_label = QtWidgets.QLabel(Form)
        self.mp10_label.setGeometry(QtCore.QRect(280, 320, 251, 16))
        self.mp10_label.setObjectName("mp10_label")
        self.lineMp10 = QtWidgets.QLineEdit(Form)
        self.lineMp10.setGeometry(QtCore.QRect(280, 340, 251, 20))
        self.lineMp10.setText("")
        self.lineMp10.setObjectName("lineMp10")
        self.lineNome = QtWidgets.QLineEdit(Form)
        self.lineNome.setGeometry(QtCore.QRect(280, 290, 251, 20))
        self.lineNome.setText("")
        self.lineNome.setObjectName("lineNome")
        self.mp10_label_2 = QtWidgets.QLabel(Form)
        self.mp10_label_2.setGeometry(QtCore.QRect(280, 270, 251, 16))
        self.mp10_label_2.setObjectName("mp10_label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.inserirButton.setText(_translate("Form", "INSERIR AMOSTRA"))
        self.label.setText(_translate("Form", "MP(2.5):"))
        self.label_2.setText(_translate("Form", "O3:"))
        self.label_3.setText(_translate("Form", "CO:"))
        self.label_4.setText(_translate("Form", "NO2:"))
        self.label_5.setText(_translate("Form", "SO2:"))
        self.mp10_label.setText(_translate("Form", "MP(10):"))
        self.mp10_label_2.setText(_translate("Form", "Nome da Amostra:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
