from PyQt5 import QtCore, QtGui, QtWidgets
import alterar, deletar, inserir


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inserirButton = QtWidgets.QPushButton(self.centralwidget)
        self.inserirButton.setGeometry(QtCore.QRect(530, 300, 191, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        self.inserirButton.setFont(font)
        self.inserirButton.setMouseTracking(False)
        self.inserirButton.setAutoFillBackground(False)
        self.inserirButton.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.inserirButton.setIconSize(QtCore.QSize(32, 32))
        self.inserirButton.setCheckable(False)
        self.inserirButton.setAutoDefault(False)
        self.inserirButton.setDefault(False)
        self.inserirButton.setFlat(False)
        self.inserirButton.setObjectName("inserirButton")
        self.airLabel = QtWidgets.QLabel(self.centralwidget)
        self.airLabel.setGeometry(QtCore.QRect(1170, 40, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.airLabel.setFont(font)
        self.airLabel.setScaledContents(False)
        self.airLabel.setObjectName("airLabel")
        self.alterarButton = QtWidgets.QPushButton(self.centralwidget)
        self.alterarButton.setGeometry(QtCore.QRect(530, 360, 191, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        self.alterarButton.setFont(font)
        self.alterarButton.setMouseTracking(False)
        self.alterarButton.setAutoFillBackground(False)
        self.alterarButton.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.alterarButton.setIconSize(QtCore.QSize(32, 32))
        self.alterarButton.setCheckable(False)
        self.alterarButton.setAutoDefault(False)
        self.alterarButton.setDefault(False)
        self.alterarButton.setFlat(False)
        self.alterarButton.setObjectName("alterarButton")
        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(440, -50, 381, 321))
        self.Logo.setSizeIncrement(QtCore.QSize(0, 0))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("../uis/imagens/LOGO GERAL.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.excluirButton = QtWidgets.QPushButton(self.centralwidget)
        self.excluirButton.setGeometry(QtCore.QRect(530, 420, 191, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        self.excluirButton.setFont(font)
        self.excluirButton.setMouseTracking(False)
        self.excluirButton.setAutoFillBackground(False)
        self.excluirButton.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.excluirButton.setIconSize(QtCore.QSize(32, 32))
        self.excluirButton.setCheckable(False)
        self.excluirButton.setAutoDefault(False)
        self.excluirButton.setDefault(False)
        self.excluirButton.setFlat(False)
        self.excluirButton.setObjectName("excluirButton")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(1110, 10, 51, 51))
        self.imageLabel.setText("")
        self.imageLabel.setPixmap(QtGui.QPixmap("../uis/imagens/air.png"))
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setObjectName("imageLabel")
        self.classificarButton = QtWidgets.QPushButton(self.centralwidget)
        self.classificarButton.setGeometry(QtCore.QRect(500, 480, 251, 35))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../uis/imagens/LOGO PEQUENA.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(17)
        self.classificarButton.setFont(font)
        self.classificarButton.setMouseTracking(False)
        self.classificarButton.setAutoFillBackground(False)
        self.classificarButton.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.classificarButton.setIconSize(QtCore.QSize(32, 32))
        self.classificarButton.setCheckable(False)
        self.classificarButton.setAutoDefault(False)
        self.classificarButton.setDefault(False)
        self.classificarButton.setFlat(False)
        self.classificarButton.setObjectName("classificarButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.inserirButton.clicked.connect(self.gotoInsert)
        self.alterarButton.clicked.connect(self.gotoAlter)
        self.excluirButton.clicked.connect(self.gotoDel)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema de Controle de Qualidade do Ar"))
        self.inserirButton.setText(_translate("MainWindow", "Inserir Amostras"))
        self.alterarButton.setText(_translate("MainWindow", "Alterar Amostras"))
        self.excluirButton.setText(_translate("MainWindow", "Excluir Amostras"))
        self.classificarButton.setText(_translate("MainWindow", "Classificar Amostras"))

    def gotoInsert(self):
        self.window = QtWidgets.QWidget()
        self.ui = inserir.Ui_Form()
        self.ui.setupUi(self.window)
        self.ui.ar = self.airLabel.text()
        self.window.show()

    def gotoAlter(self):
        self.window = QtWidgets.QWidget()
        self.ui = alterar.Ui_Form()
        self.ui.setupUi(self.window)
        self.ui.ar = self.airLabel.text()
        self.window.show()

    def gotoDel(self):
        self.window = QtWidgets.QWidget()
        self.ui = deletar.Ui_Form()
        self.ui.setupUi(self.window)
        self.ui.ar = self.airLabel.text()
        self.window.show()

