from PyQt5 import QtCore, QtGui, QtWidgets
import sql_funcs as sql


class Ui_Form(object):
    def setupUi(self, Form):
        self.ar = ''
        self.selected = ''
        Form.setObjectName("Form")
        Form.resize(798, 713)
        Form.setStyleSheet("\n"
                           "background-color: rgb(226, 226, 226);")
        self.Logo = QtWidgets.QLabel(Form)
        self.Logo.setGeometry(QtCore.QRect(250, 0, 301, 221))
        self.Logo.setStyleSheet("\n"
                                "background-color: rgb(226, 226, 226);")
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("../uis/imagens/LOGO GERAL.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.alterarButton = QtWidgets.QPushButton(Form)
        self.alterarButton.setGeometry(QtCore.QRect(250, 630, 311, 61))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../uis/imagens/LOGO PEQUENA.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(17)
        self.alterarButton.setFont(font)
        self.alterarButton.setMouseTracking(False)
        self.alterarButton.setAutoFillBackground(False)
        self.alterarButton.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.alterarButton.setIconSize(QtCore.QSize(32, 32))
        self.alterarButton.setCheckable(False)
        self.alterarButton.setAutoDefault(False)
        self.alterarButton.setDefault(False)
        self.alterarButton.setFlat(False)
        self.alterarButton.setObjectName("alterarButton")
        self.optionsButton = QtWidgets.QPushButton(Form)
        self.optionsButton.setGeometry(QtCore.QRect(580, 250, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        self.optionsButton.setFont(font)
        self.optionsButton.setMouseTracking(False)
        self.optionsButton.setAutoFillBackground(False)
        self.optionsButton.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.optionsButton.setIconSize(QtCore.QSize(32, 32))
        self.optionsButton.setCheckable(False)
        self.optionsButton.setAutoDefault(False)
        self.optionsButton.setDefault(False)
        self.optionsButton.setFlat(False)
        self.optionsButton.setObjectName("optionsButton")
        self.lineMp25 = QtWidgets.QLineEdit(Form)
        self.lineMp25.setGeometry(QtCore.QRect(280, 390, 251, 20))
        self.lineMp25.setText("")
        self.lineMp25.setObjectName("lineMp25")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(280, 370, 251, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(280, 420, 251, 16))
        self.label_2.setObjectName("label_2")
        self.lineO3 = QtWidgets.QLineEdit(Form)
        self.lineO3.setGeometry(QtCore.QRect(280, 440, 251, 20))
        self.lineO3.setText("")
        self.lineO3.setObjectName("lineO3")
        self.lineCo = QtWidgets.QLineEdit(Form)
        self.lineCo.setGeometry(QtCore.QRect(280, 490, 251, 20))
        self.lineCo.setText("")
        self.lineCo.setObjectName("lineCo")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(280, 470, 251, 16))
        self.label_3.setObjectName("label_3")
        self.lineNo2 = QtWidgets.QLineEdit(Form)
        self.lineNo2.setGeometry(QtCore.QRect(280, 540, 251, 20))
        self.lineNo2.setText("")
        self.lineNo2.setObjectName("lineNo2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(280, 520, 251, 16))
        self.label_4.setObjectName("label_4")
        self.lineSo2 = QtWidgets.QLineEdit(Form)
        self.lineSo2.setGeometry(QtCore.QRect(280, 590, 251, 20))
        self.lineSo2.setText("")
        self.lineSo2.setObjectName("lineSo2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(280, 570, 251, 16))
        self.label_5.setObjectName("label_5")
        self.mp10_label = QtWidgets.QLabel(Form)
        self.mp10_label.setGeometry(QtCore.QRect(280, 320, 251, 16))
        self.mp10_label.setObjectName("mp10_label")
        self.lineMp10 = QtWidgets.QLineEdit(Form)
        self.lineMp10.setGeometry(QtCore.QRect(280, 340, 251, 20))
        self.lineMp10.setText("")
        self.lineMp10.setObjectName("lineMp10")
        self.mp10_label_2 = QtWidgets.QLabel(Form)
        self.mp10_label_2.setGeometry(QtCore.QRect(280, 270, 251, 16))
        self.mp10_label_2.setObjectName("mp10_label_2")
        self.amostraBox = QtWidgets.QComboBox(Form)
        self.amostraBox.setGeometry(QtCore.QRect(260, 260, 301, 22))
        self.amostraBox.setObjectName("amostraBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.optionsButton.clicked.connect(self.getAms)
        self.amostraBox.activated.connect(self.getParams)
        self.alterarButton.clicked.connect(self.alterar)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Alterar Amostra"))
        self.alterarButton.setText(_translate("Form", "ALTERAR AMOSTRA"))
        self.optionsButton.setText(_translate("Form", "Obter Amostras"))
        self.label.setText(_translate("Form", "MP(2.5):"))
        self.label_2.setText(_translate("Form", "O3:"))
        self.label_3.setText(_translate("Form", "CO:"))
        self.label_4.setText(_translate("Form", "NO2:"))
        self.label_5.setText(_translate("Form", "SO2:"))
        self.mp10_label.setText(_translate("Form", "MP(10):"))

    def alterar(self):
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle('Aviso!')
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../uis/imagens/LOGO PEQUENA.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        msg.setWindowIcon(icon)
        _mp10 = self.lineMp10.text()
        _mp25 = self.lineMp25.text()
        _o3 = self.lineO3.text()
        _co = self.lineCo.text()
        _no2 = self.lineNo2.text()
        _so2 = self.lineSo2.text()
        if _mp10 and _mp25 and _o3 and _co and _no2 and _so2:
            resp = sql.alterar(self.selected, int(_mp10), int(_mp25), int(_o3), int(_co), int(_no2), int(_so2))
            msg.setText(resp)
        else:
            resp = 'TODOS OS CAMPOS PRECISAM SER PREENCHIDOS!'
            msg.setText(resp)
        x = msg.exec_()

    def getParams(self):
        values = sql.get_amostras(self.ar, self.selected)
        self.lineMp10.setText(str(values.get('mp10')))
        self.lineMp25.setText(str(values.get('mp25')))
        self.lineO3.setText(str(values.get('o3')))
        self.lineCo.setText(str(values.get('co')))
        self.lineNo2.setText(str(values.get('no2')))
        self.lineSo2.setText(str(values.get('so2')))

    def getAms(self):
        self.amostraBox.addItems(sql.usuarios('amostras', self.ar))
        self.selected = self.amostraBox.currentText()
